### ISSUE TITLE
Problem in Crousal section, not responsive in small screen 

### ISSUE THREAD

**Issue by divyansh12git** [HackSlashNITP/ByteVerse_Website#15]
Please assign this to me

![Screenshot 2024-02-01 112042](https://github.com/HackSlashNITP/ByteVerse_Website/assets/123203281/76414ae3-820e-447e-8fcd-a3bac2f8355e)

**Comment by RitwikSingh28** [comment]
@divyansh12git 
Assigned it to you. Please get it done before the deadline

**Deadline** ⏲️: February 1, 23:00 IST
